# From https://blog.somewhatabstract.com/2021/10/11/setting-up-dependabot-with-github-actions-to-approve-and-mer
name: Dependabot Pull Request Approve and Merge

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # Checking the actor will prevent your Action run failing on non-Dependabot
    # PRs but also ensures that it only does work for Dependabot PRs.
    if: ${{ github.actor == 'dependabot[bot]' }}
      steps:
        # This first step will fail if there's no metadata and so the approval
        # will not occur.
        - name: Dependabot metadata
          id: dependabot-metadata
          uses: dependabot/fetch-metadata@v1.1.1
          with:
            # populates the alert-state, ghsa-id and cvss outputs
            alert-lookup: true
             github-token: "${{ secrets.GITHUB_TOKEN }}"
        # Here the PR gets approved.
        - name: Approve a PR
          if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
          run: gh pr review --approve "$PR_URL"
          env:
            PR_URL: ${{ github.event.pull_request.html_url }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Finally, this sets the PR to allow auto-merging for patch
        # updates if all checks pass
        - name: Enable auto-merge for Dependabot PRs
          if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
          # run merge command with random delay between 1 and 120 sec.
          # this is to prevent deploy jobs from failing when multiple
          # dependabots are merged simultaneously
          run: sleep $(( ( RANDOM % 120 ) + 1 )) && gh pr merge --auto --squash "$PR_URL"
          env:
            PR_URL: ${{ github.event.pull_request.html_url }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}